sudo: required

language: python

services:
  - docker

before_install:
# keep container running (https://stackoverflow.com/questions/30209776)
- docker run -d --name app ubuntu tail -f /dev/null

script:
- docker exec app apt-get update
- docker exec app apt-get install -qq gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-pango-1.0 gir1.2-webkit2-4.0 git python3 python3-enchant python3-gi python3-pip python3-yaml
- docker exec app pip3 install -U pip tox
# see https://github.com/travis-ci/travis-ci/issues/6652
- docker exec app git clone --depth=50 --branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}" "https://github.com/${TRAVIS_PULL_REQUEST_SLUG:-$TRAVIS_REPO_SLUG}.git" "/home/${TRAVIS_REPO_SLUG}"
- docker exec app tox -c "/home/${TRAVIS_REPO_SLUG}"

after_script:
- docker rm -f app

notifications:
  email:
    on_success: change
    on_failure: always
